---
title: "君にもできる！<br/>AutoML Tables"
date: 2023-05-14
date-format: "YYYY年 M月 D日"
event_link: "[GCPUG in Shiga #3 「はじめてのAutoML・BigQuery」](https://gcpug-shiga.connpass.com/event/276076/)"

event_name: "GCPUG in Shiga #3 「はじめてのAutoML・BigQuery」"
format:
  html:
    toc: true
---

# はじめに (1分)

## 自己紹介

## ご注意とお詫び

- AutoML Tables は非推奨となり、2024 年 1 月 23 日以降は Google Cloud で使用できなくなります。
- 本発表内容は Vertex AI / 表形式のデータ / AutoML を使うことを前提として構成しています

# ところで……（背景） (2分)

## 最近は、魔法使いの修行が流行っている？

- AI (ChatGPTとか) に呪文をかけて、望みの文章を生み出す
- AI (Stable Diffusionとか) に呪文をかけて、望みの画像を生み出す
- AI (MusicLMとか) に呪文をかけて、望みの音楽を生み出す

→よりよい呪文を作ったり、よりよい AI と呪文の組み合わせの研究に励む人々がたくさん！

## 「呪文」をかける対象の AI を育てる

- まずは呪文をかける対象の AI を育てる必要がある
- データをたくさん AI に与えることで、成長する
  - これが世にいう「学習」と呼ばれるプロセス
- 成長した AI に呪文をかけて、望みの結果を生み出す

# そうは言ってもね…… (0.5分)

- 「呪文」を作るのはできそうだけど、AI を成長させる方法はわからない……
- 今から AI の仕組みを勉強するのは大変だ……
- 本当に役にたつものが生み出せるのかわからない……

→AI を自動で成長させてくれる AutoML を使って、Excel データで育て始めてみませんか？

# Vertex AI / 表形式のデータ でできること (3分)

- AI に与えるデータ自体を管理できる
- AI に与えるデータを指定すれば、自動で AI を育ててくれる (AutoML)
- AI の成長状態を記録・管理できる
- 育てた AI に呪文をかけて、何かを生み出すことができる
  - 表形式データの場合は、予測値（単体値・連続値）もしくは分類の予測結果を生み出す

# 呪文をかけて何かを生み出すまでの道のり (2.5分)

1. 何を生み出したいか、目的を定義する
2. AI を育てるためのデータを収集する
3. AI を育てるためのデータを準備する
4. 学習をさせて AI を育てる
5. 育てた AI に呪文をかけて何かを生み出す

# Excel データで始めてみませんか？ (0.5分)

# 宣伝 (0.5分)

# ご清聴ありがとうございました

# Appendix

- 料金
  - 学習 : 1時間で 2300円ほど
